# Generated by Django 4.2.5 on 2023-10-02 09:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="appuser",
            managers=[
                ("objects", users.models.AppUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
