# Generated by Django 4.2.6 on 2023-10-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_appuser_activation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="activation_code_valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
