# Generated by Django 4.2.6 on 2023-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_recipeingredient"),
        ("users", "0004_appuser_activation_code_valid_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="favorites_recipes",
            field=models.ManyToManyField(to="recipes.recipe"),
        ),
    ]
