# Generated by Django 4.2.7 on 2024-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
