# Generated by Django 4.2.6 on 2023-10-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0002_category_name"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "difficulty_level",
                    models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
                ),
                ("execution_time", models.IntegerField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="tags.tag")),
            ],
        ),
    ]
