# Generated by Django 4.2.6 on 2023-11-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_recipe_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.CharField(max_length=20)),
                ("amount", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("gr", "gram"),
                            ("kg", "kilogram"),
                            ("ml", "milliliter"),
                            ("l", "liter"),
                            ("tsp", "teaspoon"),
                            ("tbsp", "tablespoon"),
                            ("piece", "piece"),
                        ],
                        default="gr",
                        max_length=15,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
    ]
