# Generated by Django 4.2.6 on 2023-11-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_recipereview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipereview",
            name="review",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
