# Generated by Django 4.2.6 on 2023-11-13 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_alter_recipereview_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipereview",
            old_name="user",
            new_name="author",
        ),
    ]
